# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build SecondJob changed!
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployFirstJob
    steps:
    - bash: echo DevDeploy FirstJob
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployFirstJob
    steps:
    - bash: echo QADeploy FirstJob
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployFirstJob
    steps:
    - bash: echo ProdDeploy FirstJob
